namespace: tp7-kustomize

  # On garde `images:` pour piloter le tag depuis l'overlay (démonstration rollout)
  # Ici on ne change pas le repository, seulement la version (newTag)
images:
- name: ghcr.io/LionelGuez/spring-petclinic
  newName: ghcr.io/LionelGuez/spring-petclinic
  newTag: 1578921164fdb2d76b30b89bf44ffb7b5eafd75e
- name: ghcr.io/lionelguez/spring-petclinic
  newName: ghcr.io/lionelguez/spring-petclinic
  newTag: 4.0.1-SNAPSHOT

# Référencer la baseline (réutiliser tous les manifests de base/)
resources:
- ../base

# Appliquer les patches (modifications)
  # Type 1 : JSON Patch (replicas.yaml) - syntaxe très spécifique, ex: /spec/replicas
patches:
- path: replicas.yaml
  target:
    kind: Deployment
    name: clinic-deploy
- path: patch-routing.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
